/* GET requests */
curl -v localhost:8080/test -X GET
curl -v localhost:8080/relative/path/test -X GET
curl -v localhost:8080/absolute/path/test -X GET

/* Path params */
http://localhost:8080/user/dhanushka
http://localhost:8080/users/dhanushka/asela/deneth

/* Request params */
http://localhost:8080/details?first_name=dhanushka&age=23

/* Payloads */
http://localhost:8080/setStudent
{
  "name": "Dhanushka",
  "age": 22
}
