[package]
org = "wso2healthcare"
name = "wso2healthcare_healthcare_fhir_r4_api_practitioner"
version = "0.1.1"
export = ["wso2healthcare_healthcare_fhir_r4_api_practitioner"]
distribution = "2201.1.2"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Practitioner","r4","international"]

[build-options]
observabilityIncluded = true
