[package]
org = "wso2"
name = "data_mapper_hl7v23_fhir_mapping"
version = "0.1.0"
distribution = "2201.2.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7"
version = "0.1.7"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7v23"
version = "0.1.9"
repository="local"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7v24"
version = "0.1.9"
repository="local"
