### Get patient resource by id
GET http://localhost:8080/api/v1/Patient/7199937

### Post patient resource
POST http://localhost:8080/api/v1
Content-Type: application/json

{
  "resourceType": "Patient",
  "name": [
    {
      "use": "official",
      "given": ["Dhanushka"],
      "family": "Sandakelum"
    }
  ],
  "gender": "male",
  "birthDate": "1999-11-12",
  "telecom": [
    { "system": "phone", "value": "0775642956", "use": "mobile" },
    { "system": "email", "value": "dhanushka@gmail.com" }
  ],
  "address": [
    {
      "line": ["131/C School Road"],
      "city": "Kahatapitiya",
      "state": "Hanwella",
      "country": "Sri Lanka",
      "postalCode": "10650"
    }
  ]
}

### Patch patient resource
PATCH  http://localhost:8080/api/v1
Content-Type: application/json

{
  "resourceType": "Patient",
  "id": "7199937",
  "name": [
    {
      "use": "official",
      "given": ["Dhanushkayaaa"],
      "family": "Sandakelum"
    }
  ],
  "gender": "male",
  "birthDate": "1999-11-12",
  "telecom": [
    { "system": "phone", "value": "0775642956", "use": "mobile" },
    { "system": "email", "value": "dhanushka@gmail.com" }
  ],
  "address": [
    {
      "line": ["131/C School Road"],
      "city": "Kahatapitiya",
      "state": "Hanwella",
      "country": "Sri Lanka",
      "postalCode": "10650"
    }
  ]
}

### Delete patient resource by id
DELETE  http://localhost:8080/api/v1/Patient/7199497