[package]
org = "wso2"
name = "database_crud"
version = "0.1.0"
distribution = "2201.2.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"